In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
'the glass of juice',
'the cup of tea',
'Iam a good boy',
'Iam a good developer',
'understand the meaning of words',
'your videos are good']

In [6]:
#defining the vocabulary size
voc_size = 10000

In [7]:
# Ohe representation
one_hot_repr =  [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[8474, 2463, 659, 4945],
 [8474, 2463, 659, 9075],
 [8474, 9566, 659, 3498],
 [4521, 8581, 9116, 2188],
 [4521, 8581, 9116, 7808],
 [7774, 8474, 7888, 659, 7570],
 [7642, 9551, 4225, 9116]]

In [8]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [10]:
sent_length =8
embedd_docs = pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)

In [11]:
print(embedd_docs)

[[   0    0    0    0 8474 2463  659 4945]
 [   0    0    0    0 8474 2463  659 9075]
 [   0    0    0    0 8474 9566  659 3498]
 [   0    0    0    0 4521 8581 9116 2188]
 [   0    0    0    0 4521 8581 9116 7808]
 [   0    0    0 7774 8474 7888  659 7570]
 [   0    0    0    0 7642 9551 4225 9116]]


In [12]:
#feature representation
dim = 10

In [15]:
#feature representation
dim = 10
model= Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

d:\Project\imdb\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedd_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step


array([[[-0.03876805,  0.02035475, -0.04657997, -0.02816085,
         -0.02009933,  0.01205325, -0.00309125,  0.04498306,
          0.02952078, -0.04627041],
        [-0.03876805,  0.02035475, -0.04657997, -0.02816085,
         -0.02009933,  0.01205325, -0.00309125,  0.04498306,
          0.02952078, -0.04627041],
        [-0.03876805,  0.02035475, -0.04657997, -0.02816085,
         -0.02009933,  0.01205325, -0.00309125,  0.04498306,
          0.02952078, -0.04627041],
        [-0.03876805,  0.02035475, -0.04657997, -0.02816085,
         -0.02009933,  0.01205325, -0.00309125,  0.04498306,
          0.02952078, -0.04627041],
        [ 0.02221331,  0.02094075,  0.0276271 , -0.02112329,
          0.02567923, -0.04180073,  0.03504521, -0.00485643,
         -0.00382058, -0.00299473],
        [ 0.04179367, -0.015659  ,  0.04785005,  0.02376339,
          0.04953953,  0.0328859 ,  0.0168733 ,  0.03138578,
         -0.00553453,  0.04166416],
        [ 0.02544092,  0.01388783,  0.00567083,  0.0